context:
  version: "1.5.0"
  python_min: 3.10

recipe:
  name: pydantic_ai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pydantic-ai/pydantic_ai-${{ version }}.tar.gz
    sha256: e16bda3c6e0c117f16013c654b4bcff04efb2d8482a9a220926d1faed37902ae
    target_directory: pydantic-ai/
  - url: https://pypi.org/packages/source/p/pydantic-ai-slim/pydantic_ai_slim-${{ version }}.tar.gz
    sha256: e75f9fecde384296f7cd5ce47b320f96df893395f4d6542ed03c43424a3cc2e2
    target_directory: pydantic-ai-slim/
  - url: https://pypi.org/packages/source/p/pydantic-graph/pydantic_graph-${{ version }}.tar.gz
    sha256: 747802da8603c83254fb32ec3ec1a0fa1c085e3655521af3fc57c1b2335e2ab9
    target_directory: pydantic-graph/
  - url: https://pypi.org/packages/source/p/pydantic-evals/pydantic_evals-${{ version }}.tar.gz
    sha256: f5b1e6606d152b211e4b59eee10a49d976e0f092030cc3f7b86441e713b3a1c6
    target_directory: pydantic-evals/

build:
  number: 0

outputs:
  - package:
      name: pydantic-graph
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-graph -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - httpx >=0.27
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_graph
          pip_check: true

    about:
      license_file: pydantic-graph/LICENSE

  - package:
      name: pydantic-ai-slim
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-ai-slim -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - eval-type-backport >=0.2.0
        - exceptiongroup
        - griffe >=1.3.2
        - httpx >=0.27
        - pydantic >=2.10
        - pydantic-graph =${{ version }}
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0
        - genai-prices >=0.0.22

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

    about:
      license_file: pydantic-ai-slim/LICENSE

  - package:
      name: pydantic-ai
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-ai -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - pydantic-ai-slim =${{ version }}
        - logfire >=3.11.0
        - openai >=1.99.9
        - google-auth >=2.36.0
        - requests >=2.32.2
        - anthropic >=0.49.0
        - groq >=0.15.0
        - boto3 >=1.35.74
        - pydantic-evals =${{ version }}
        - fasta2a >=0.4.1

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

    about:
      license_file: pydantic-ai/LICENSE

  - package:
      name: pydantic-evals
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-evals -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - anyio
        - eval-type-backport >=0.2.0
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - pydantic-ai-slim =${{ version }}
        - pyyaml >=6.0.2
        - rich >=13.9.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_evals
          pip_check: true

    about:
      license_file: pydantic-evals/LICENSE

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: pydantic-ai/LICENSE

extra:
  feedstock-name: pydantic-ai
  recipe-maintainers:
    - moritzwilksch
