context:
  version: "1.41.0"
  python_min: 3.10

recipe:
  name: pydantic_ai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pydantic-ai/pydantic_ai-${{ version }}.tar.gz
    sha256: 81fb9f12103c36c6ff565edab40638aa905965b9fd5d0e37ed0b769fd342ce50
    target_directory: pydantic-ai/
  - url: https://pypi.org/packages/source/p/pydantic-ai-slim/pydantic_ai_slim-${{ version }}.tar.gz
    sha256: a7499b92ba5c82394aa086cbbd9ef66501dafdf34b8a72183e220fc6f6a0e159
    target_directory: pydantic-ai-slim/
  - url: https://pypi.org/packages/source/p/pydantic-graph/pydantic_graph-${{ version }}.tar.gz
    sha256: 63c447431ef1c9abef597c03553dfbf3aab26ef79c70c92d6f8b545a3abbbfa8
    target_directory: pydantic-graph/
  - url: https://pypi.org/packages/source/p/pydantic-evals/pydantic_evals-${{ version }}.tar.gz
    sha256: bfe694694a8966b06bf8a966030e5cc2ad8f8fc6c0195995f6cb73e27b28a3a7
    target_directory: pydantic-evals/

build:
  number: 0

outputs:
  - package:
      name: pydantic-graph
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-graph -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - httpx >=0.27
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_graph
          pip_check: true

    about:
      license_file: pydantic-graph/LICENSE

  - package:
      name: pydantic-ai-slim
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-ai-slim -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - eval-type-backport >=0.2.0
        - exceptiongroup
        - griffe >=1.3.2
        - httpx >=0.27
        - pydantic >=2.10
        - pydantic-graph =${{ version }}
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0
        - genai-prices >=0.0.40

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

    about:
      license_file: pydantic-ai-slim/LICENSE

  - package:
      name: pydantic-ai
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-ai -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - pydantic-ai-slim =${{ version }}
        - logfire >=3.11.0
        - openai >=1.99.9
        - google-auth >=2.36.0
        - requests >=2.32.2
        - anthropic >=0.49.0
        - groq >=0.15.0
        - boto3 >=1.35.74
        - pydantic-evals =${{ version }}
        - fasta2a >=0.4.1

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

    about:
      license_file: pydantic-ai/LICENSE

  - package:
      name: pydantic-evals
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-evals -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - anyio
        - eval-type-backport >=0.2.0
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - pydantic-ai-slim =${{ version }}
        - pyyaml >=6.0.2
        - rich >=13.9.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_evals
          pip_check: true

    about:
      license_file: pydantic-evals/LICENSE

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: pydantic-ai/LICENSE

extra:
  feedstock-name: pydantic-ai
  recipe-maintainers:
    - moritzwilksch
