context:
  version: "0.3.4"

recipe:
  name: pydantic_ai
  version: ${{ version }}

build:
  number: 1

outputs:
  - package:
      name: pydantic-graph
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-graph/pydantic_graph-${{ version }}.tar.gz
        sha256: 1172dccd8bfcc742f4eb52aa4199daa3cdb6446e726fb6960667d49a02c4df02

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - httpx >=0.27
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_graph
          pip_check: true

  - package:
      name: pydantic-ai-slim
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-ai-slim/pydantic_ai_slim-${{ version }}.tar.gz
        sha256: f25fd8798ecc9f928d251b2b38d777c22684aa2e89d459fd64cc2a0b5ecb0fed

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - eval-type-backport >=0.2.0
        - exceptiongroup
        - griffe >=1.3.2
        - httpx >=0.27
        - pydantic >=2.10
        - pydantic-graph =${{ version }}
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

  - package:
      name: pydantic-ai
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-ai/pydantic_ai-${{ version }}.tar.gz
        sha256: 74c868fb9bbb89f392d43b77dc3a6532ccc8f4a1717ccca0801797af7bc59c05

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - pydantic-ai-slim =${{ version }}
        - logfire >=3.11.0
        - openai >=1.75.0
        - google-auth >=2.36.0
        - requests >=2.32.2
        - anthropic >=0.49.0
        - groq >=0.15.0
        - boto3 >=1.35.74
        - pydantic-evals =${{ version }}
        - fasta2a =${{ version }}

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

  - package:
      name: pydantic-evals
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-evals/pydantic_evals-${{ version }}.tar.gz
        sha256: 51c1f2992c2b9b07d981df0e44450cf79b84ef7c5b8645395c7126c617e4f915

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - anyio
        - eval-type-backport >=0.2.0
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - pydantic-ai-slim =${{ version }}
        - pyyaml >=6.0.2
        - rich >=13.9.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_evals
          pip_check: true

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: LICENSE

extra:
  feedstock-name: pydantic-ai
  recipe-maintainers:
    - moritzwilksch
