context:
  version: "0.0.40"

recipe:
  name: pydantic_ai
  version: ${{ version }}

source:
  - url: https://github.com/pydantic/pydantic-ai/archive/refs/tags/v${{ version }}.tar.gz
    sha256: d83fbc5e5dd47b98a9cdbf13e67a7bcdc34267c8e553ae4692420cc03ab09c7e

build:
  number: 0

outputs:
  - package:
      name: pydantic-graph
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic_graph/ -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
      run:
        - python >=${{ python_min }}
        - logfire-api
        - pydantic
        - typing-inspection
        - httpx

    tests:
      - python:
          python_version: ${{ python_min }}
          imports:
            - pydantic_graph
          pip_check: true

  - package:
      name: pydantic-ai
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic_ai_slim/ -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
      run:
        - python >=${{ python_min }}
        - logfire-api
        - pydantic-graph
        - griffe
        - eval-type-backport
        - opentelemetry-api >=1.28.0
        - if: match(python, "<3.10")
          then:
            - typing-extensions

    tests:
      - python:
          python_version: ${{ python_min }}
          imports:
            - pydantic_ai
          pip_check: true

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
