context:
  version: "0.2.18"

recipe:
  name: pydantic_ai
  version: ${{ version }}

build:
  number: 0

outputs:

  - package:
      name: fasta2a
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/f/fasta2a/fasta2a-${{ version }}.tar.gz
        sha256: 24cc34fdc9d2ea1a9d7aadc1864a47704d2576078113eaafad6344297ee13e02

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - starlette >0.29.0
        - pydantic >=2.10
        - opentelemetry-api >=1.28.0
        - eval-type-backport >=0.2.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - fasta2a
          pip_check: true

  - package:
      name: pydantic-graph
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-graph/pydantic_graph-${{ version }}.tar.gz
        sha256: 3346bacfe368ce18ddab7a70f7d138b781b7b459101c1e330d97c93d489334b6

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - httpx >=0.27
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_graph
          pip_check: true

  - package:
      name: pydantic-ai-slim
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-ai-slim/pydantic_ai_slim-${{ version }}.tar.gz
        sha256: 2e3ebfded404b1c223e30e69517c9bf669344fff0cf2787d67ba086862a22b9a

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - eval-type-backport >=0.2.0
        - exceptiongroup
        - griffe >=1.3.2
        - httpx >=0.27
        - pydantic >=2.10
        - pydantic-graph =${{ version }}
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

  - package:
      name: pydantic-ai
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-ai/pydantic_ai-${{ version }}.tar.gz
        sha256: 295e03fd243e431ebcede45878b59d227aa020287f3180ebbcc2957b969de6ac

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - pydantic-ai-slim =${{ version }}
        - logfire >=3.11.0
        - openai >=1.75.0
        - google-auth >=2.36.0
        - requests >=2.32.2
        - anthropic >=0.49.0
        - groq >=0.15.0
        - boto3 >=1.35.74
        - pydantic-evals =${{ version }}
        - fasta2a =${{ version }}

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

  - package:
      name: pydantic-evals
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-evals/pydantic_evals-${{ version }}.tar.gz
        sha256: e69cc41f78b613afba06c9156cd53593f05b04a12dd0cabe79caf8d3547d169c

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - anyio
        - eval-type-backport >=0.2.0
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - pydantic-ai-slim =${{ version }}
        - pyyaml >=6.0.2
        - rich >=13.9.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_evals
          pip_check: true

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: LICENSE

extra:
  feedstock-name: pydantic-ai
  recipe-maintainers:
    - moritzwilksch
