context:
  version: "0.2.6"

recipe:
  name: pydantic_ai
  version: ${{ version }}

source:
  - url: https://github.com/pydantic/pydantic-ai/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 87fb99b50b2d5c0c4165bf9574cfd990c310d0c7157b4ab9287a339b826fc0b0

build:
  number: 0

outputs:
  - package:
      name: pydantic-graph
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic_graph/ -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning =0.7.0
      run:
        - python >=${{ python_min }}
        - logfire-api
        - pydantic
        - opentelemetry-api >=1.28.0
        - typing-inspection
        - httpx

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_graph
          pip_check: true

  - package:
      name: pydantic-ai
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic_ai_slim/ -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning =0.7.0
      run:
        - python >=${{ python_min }}
        - logfire-api
        - pydantic-graph =${{ version }}
        - griffe
        - eval-type-backport
        - opentelemetry-api >=1.28.0
        - if: match(python, "<3.10")
          then:
            - typing-extensions

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

  - package:
      name: pydantic-evals
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic_evals/ -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning =0.7.0
      run:
        - python >=${{ python_min }}
        - pydantic-ai =${{ version }}
        - rich >=13.9.4
        - logfire-api >=1.2.0
        - pydantic >=2.10
        - pyyaml >=6.0.2
        - anyio
        - eval-type-backport
        - opentelemetry-sdk

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_evals
          pip_check: true

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
