context:
  version: "0.0.29"

recipe:
  name: pydantic_ai
  version: ${{ version }}

source:
  - url: https://github.com/pydantic/pydantic-ai/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 33e501c10526adb3852f0c6545e95894b23429a8e3abcdc97eb1f17c5a983dda

build:
  number: 0

outputs:
  - package:
      name: pydantic-graph
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic_graph/ -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
      run:
        - python >=${{ python_min }}
        - logfire-api
        - pydantic
        - httpx

    tests:
      - python:
          imports:
            - pydantic_graph
          pip_check: true

  - package:
      name: pydantic-ai
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic_ai_slim/ -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
      run:
        - python >=${{ python_min }}
        - logfire-api
        - pydantic-graph
        - griffe
        - eval-type-backport
        - if: match(python, "<3.10")
          then:
            - typing-extensions

    tests:
      - python:
          imports:
            - pydantic_ai
          pip_check: true

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
