context:
  version: "1.95.0"
  python_min: "3.10"

recipe:
  name: pydantic_ai
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pydantic-ai/pydantic_ai-${{ version }}.tar.gz
    sha256: 164ada3a57a16ad49ae0e891f18ebcb1dc92406a068ccd3558214dbb074da328
    target_directory: pydantic-ai/
  - url: https://pypi.org/packages/source/p/pydantic-ai-slim/pydantic_ai_slim-${{ version }}.tar.gz
    sha256: 2057b2a6280022145a9d00d5b103bfb2a7b54be2f6bffa3fa5e8d41561c59dc1
    target_directory: pydantic-ai-slim/
  - url: https://pypi.org/packages/source/p/pydantic-graph/pydantic_graph-${{ version }}.tar.gz
    sha256: 66ebe9f6ef49026e84a60e8ebcd708f46e6d35da35d9139dea0268d552ce6b14
    target_directory: pydantic-graph/
  - url: https://pypi.org/packages/source/p/pydantic-evals/pydantic_evals-${{ version }}.tar.gz
    sha256: d314889be91f4d07d0d698f8dfb240f635f7da1919090fc6b287c5b6c5479608
    target_directory: pydantic-evals/

build:
  number: 0

outputs:
  - package:
      name: pydantic-graph
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-graph -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - httpx >=0.27
        - logfire-api >=3.14.1
        - pydantic >=2.12
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_graph
          pip_check: true

    about:
      license_file: pydantic-graph/LICENSE

  - package:
      name: pydantic-ai-slim
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-ai-slim -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - griffelib >=2.0
        - httpx >=0.27
        - pydantic >=2.12
        - pydantic-graph =${{ version }}
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0
        - genai-prices >=0.0.48

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

    about:
      license_file: pydantic-ai-slim/LICENSE

  - package:
      name: pydantic-ai
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-ai -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - pydantic-ai-slim =${{ version }}
        - logfire >=4.16.0
        - openai >=2.11.0
        - tiktoken >=0.12.0
        - google-genai >=1.56.0
        - google-auth >=2.36.0
        - requests >=2.32.2
        - anthropic >=0.80.0
        - groq >=0.25.0
        - boto3 >=1.42.14
        - pydantic-evals =${{ version }}
        - fasta2a >=0.4.1

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

    about:
      license_file: pydantic-ai/LICENSE

  - package:
      name: pydantic-evals
      version: ${{ version }}

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install ./pydantic-evals -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - anyio
        - logfire-api >=3.14.1
        - pydantic >=2.12
        - pydantic-ai-slim =${{ version }}
        - pyyaml >=6.0.2
        - rich >=13.9.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_evals
          pip_check: true

    about:
      license_file: pydantic-evals/LICENSE

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_file: pydantic-ai/LICENSE

extra:
  feedstock-name: pydantic-ai
  recipe-maintainers:
    - moritzwilksch
