context:
  version: "0.2.4"

recipe:
  name: pydantic_ai
  version: ${{ version }}

build:
  number: 1

outputs:

  - package:
      name: fasta2a
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/f/fasta2a/fasta2a-${{ version }}.tar.gz
        sha256: 7afa3fd3205ce3f299b68b2705d285380328a7a4cbd2d230230e66b4701743e8

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - starlette >0.29.0
        - pydantic >=2.10
        - opentelemetry-api >=1.28.0
        - eval-type-backport >=0.2.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - fasta2a
          pip_check: true

  - package:
      name: pydantic-graph
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-graph/pydantic_graph-${{ version }}.tar.gz
        sha256: e01cec584b7d53186ff58e0c673d8d55244b87783932028e4b0f49a5800a1e8c

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - httpx >=0.27
        - logfire-api >=1.2.0
        - opentelemetry-api >=1.28.0
        - pydantic >=2.10
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_graph
          pip_check: true

  - package:
      name: pydantic-ai-slim
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-ai-slim/pydantic_ai_slim-${{ version }}.tar.gz
        sha256: 498ab56e6b00ce2cc28c7c6da536c78a7665ef1345330bfe025e8376529bd296

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - eval-type-backport >=0.2.0
        - exceptiongroup
        - griffe >=1.3.2
        - httpx >=0.27
        - pydantic >=2.10
        - pydantic-graph =${{ version }}
        - opentelemetry-api >=1.28.0
        - typing-inspection >=0.4.0

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

  - package:
      name: pydantic-ai
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-ai/pydantic_ai-${{ version }}.tar.gz
        sha256: f80820f4b84d35c9155cf5bd79881576eca141f7b7a232ed840811a4307ee0ea

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - pydantic-ai-slim =${{ version }}
        - logfire >=3.11.0
        - openai >=1.75.0
        - google-auth >=2.36.0
        - requests >=2.32.2
        - anthropic >=0.49.0
        - groq >=0.15.0
        - boto3 >=1.35.74
        - pydantic-evals =${{ version }}
        - fasta2a =${{ version }}

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_ai
          pip_check: true

  - package:
      name: pydantic-evals
      version: ${{ version }}

    source:
      - url: https://pypi.org/packages/source/p/pydantic-evals/pydantic_evals-${{ version }}.tar.gz
        sha256: a5b21e6235975a4b3d40d33c7a76234d6435de07bd6709a2296452933f8ba111

    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv

    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - hatchling
        - uv-dynamic-versioning
      run:
        - python >=${{ python_min }}
        - anyio
        - eval-type-backport >=0.2.0
        - logfire-api >=1.2.0
        - opentelemetry-sdk
        - pydantic >=2.10
        - pydantic-ai-slim =${{ version }}
        - pyyaml >=6.0.2
        - rich >=13.9.4

    tests:
      - python:
          python_version: ${{ python_min }}.*
          imports:
            - pydantic_evals
          pip_check: true

about:
  homepage: https://ai.pydantic.dev/
  summary: Agent Framework / shim to use Pydantic with LLMs
  documentation: https://ai.pydantic.dev
  license: MIT
  license_url: https://raw.githubusercontent.com/pydantic/pydantic-ai/refs/tags/v${{ version }}/LICENSE

extra:
  feedstock-name: pydantic-ai
  recipe-maintainers:
    - moritzwilksch
